### ISSUE TITLE
`degu-image` needs the ability to specify custom google image parameters

### ISSUE THREAD

**Issue by jeremydw** [blinkk/degu#215]
Sometimes we want to specify things like the quality level (e.g. `v1`) manually. The `degu-image` should support some kind of attribute for overwriting or supplanting google image parameters, e.g.

```<degu-image google-params="v1-cc" src="..."></degu-image>```

The `v1-cc` would either override or append to the default image params.

**Comment by uxder** [comment]
Checked in with v2.4.0

Let me know if you have any issues.  Thanks

**Comment by willthomson** [comment]
@uxder I'm seeing an issue where adding `google-params="v1"` removes some of the default params. For instance, without the attribute, by default I'd see something like `=rw-e365-w2000` and after, it's `=w2000-v1`. Would it be possible to modify this so that any specified parameters are additional, rather than an override? In this instance I'd like to see `=rw-e365-w2000-v1`. Thanks!

**Comment by uxder** [comment]
Updated!  It's available in v2.4.2
